-- =============================================================================
-- Fox — pendências aprovadas
--
-- ⚠️  NÃO rode este arquivo inteiro de uma vez.
--     O Postgres exige COMMIT do novo enum antes de usá-lo (erro 55P04).
--
-- Ordem obrigatória no Lovable SQL Editor:
--   1) fox_pendencias_aprovadas_passo1_icms_enum.sql  → Run
--   2) fox_pendencias_aprovadas_passo2.sql            → Run
-- =============================================================================
